language: php
php:
  - '5.6'

before_script:
  - composer global require squizlabs/php_codesniffer
  - composer global require phpmd/phpmd
  - composer global require sebastian/phpcpd

script:
  - ~/.composer/vendor/bin/phpcs --standard=PSR2 src/
